### ISSUE TITLE
Fail to update target temp sensor

### ISSUE THREAD

**Issue by scacner** [scacner/badnest#3]
From logs:

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 404, in _async_run
return await self.script.async_run(variables, context)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1212, in async_run
await asyncio.shield(run.async_run())
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
await service_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1435, in async_call
processed_data = handler.schema(service_data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
return self._exec((Schema(val) for val in self.validators), v)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
raise e if self.msg is None else AllInvalid(self.msg, path=path)
File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
v = func(v)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
return schema(data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['sensor']
2021-05-28 19:00:29 ERROR (MainThread) [homeassistant.components.script.nest_set_downstairs_as_target_temp] Nest: Set Downstairs as Target Temp: Error executing script. Invalid data for call_service at pos 1: required key not provided @ data['sensor']
2021-05-28 19:00:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```

**Comment by scacner** [comment]
There was no visual field for selecting the sensor to use in HA. Manually adding a `sensor` kay, value pairing fixes this issue. Going to see if there's a way to add in the visual field to HA interface.
